analyzer:
  exclude:
    - build/**

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_lambdas: true
    use_super_parameters: true
